/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import GestioneEntita.GestioneAnagDip;
import GestioneEntita.GestioneDitte;
import GestioneEntita.GestionePermanenza;
import GestioneEntita.GestioneTask;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author giandomenico
 */
public class JPanelArchivio extends javax.swing.JPanel {

    private boolean dipendente;
    private int mode = 0;
    /**
     * Creates new form JPanelArchivio
     */
    public JPanelArchivio() throws SQLException {
        initComponents();
        registroPermanenze();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonAggiungi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonStipendio = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jPanelCheckBoxes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioID = new javax.swing.JRadioButton();
        JRadioDataInizio = new javax.swing.JRadioButton();
        jRadioDataFine = new javax.swing.JRadioButton();

        setName("Archivio"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanenze", "Ospiti", "Dipendenti", "Ditte esterne", "Task completati" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Selezionare il registro");
        jLabel1.setName("Archivio"); // NOI18N

        jButtonAggiungi.setText("Aggiungi");
        jButtonAggiungi.setEnabled(false);
        jButtonAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAggiungiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 1000));
        jScrollPane1.setViewportView(jTable1);

        jButtonStipendio.setText("Aggiorna stipendio");
        jButtonStipendio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStipendioActionPerformed(evt);
            }
        });

        jLabelInfo.setText("jLabel2");

        jLabel2.setText("Ordina Per");

        buttonGroup1.add(jRadioID);
        jRadioID.setSelected(true);
        jRadioID.setText("ID");
        jRadioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioIDActionPerformed(evt);
            }
        });

        buttonGroup1.add(JRadioDataInizio);
        JRadioDataInizio.setText("Data Inizio");
        JRadioDataInizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioDataInizioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDataFine);
        jRadioDataFine.setText("Data Fine");
        jRadioDataFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDataFineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCheckBoxesLayout = new javax.swing.GroupLayout(jPanelCheckBoxes);
        jPanelCheckBoxes.setLayout(jPanelCheckBoxesLayout);
        jPanelCheckBoxesLayout.setHorizontalGroup(
            jPanelCheckBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckBoxesLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRadioDataInizio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioDataFine)
                .addContainerGap())
        );
        jPanelCheckBoxesLayout.setVerticalGroup(
            jPanelCheckBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckBoxesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioID)
                    .addComponent(JRadioDataInizio)
                    .addComponent(jRadioDataFine))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonStipendio, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInfo)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCheckBoxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCheckBoxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAggiungi)
                    .addComponent(jButtonStipendio))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(449, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        try {
            int index = jComboBox1.getSelectedIndex();
            switch(index) {
                case 0:
                registroPermanenze();
                break;
                case 1:
                registroOspiti();
                break;
                case 2:
                registroDipendenti();
                break;
                case 3:
                registroDitteEsterne();
                break;
                case 4:
                registroTask();
                break;

            }
        } catch (SQLException ex) {
            Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAggiungiActionPerformed

        if(dipendente) {
            new JDialogOspDip(null, true, false).setVisible(true);
        } else {
            new JDialogDittaEsterna(null, true).setVisible(true);
        }
    }//GEN-LAST:event_jButtonAggiungiActionPerformed

    private void jButtonStipendioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStipendioActionPerformed
        
        int index = jTable1.getSelectedRow();
        System.out.println("Riga: " + index);
        int nuovoS = Integer.parseInt(JOptionPane.showInputDialog("Inserire nuovo stipendio"));
        while(!new GestioneAnagDip().aggiornaStipendio(index, nuovoS))
        {}
        try {
            registroDipendenti();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelArchivio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonStipendioActionPerformed

    private void jRadioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioIDActionPerformed
        mode = 0;
        try {
            registroTask();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelArchivio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioIDActionPerformed

    private void JRadioDataInizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioDataInizioActionPerformed
        mode = 1;
        try {
            registroTask();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelArchivio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JRadioDataInizioActionPerformed

    private void jRadioDataFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDataFineActionPerformed
        mode = 2;
        try {
            registroTask();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelArchivio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioDataFineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRadioDataInizio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAggiungi;
    private javax.swing.JButton jButtonStipendio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JPanel jPanelCheckBoxes;
    private javax.swing.JRadioButton jRadioDataFine;
    private javax.swing.JRadioButton jRadioID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void registroPermanenze() throws SQLException{
        
        Vector colonne = new Vector();
        colonne.add("Nome");
        colonne.add("Cognome");
        colonne.add("Codice fiscale");
        colonne.add("Stanza");
        colonne.add("Data arrivo");
        colonne.add("Data partenza");
        
        Vector dati = GestionePermanenza.permanenzeConcluse();
        
        jPanelCheckBoxes.setVisible(false);
        jTable1.setModel(new DefaultTableModel(dati, colonne));
        jButtonAggiungi.setEnabled(false);
        jButtonStipendio.setEnabled(false);
        jLabelInfo.setText("#Permanenze per codice fiscale unico: "+GestionePermanenza.contaPermanenzeUniche());
    }
    
    private void registroOspiti() throws SQLException{
        
        Vector colonne = new Vector();
        colonne.add("Nome");
        colonne.add("Cognome");
        colonne.add("Codice fiscale");
        colonne.add("Data di nascita");
        colonne.add("Numero documento");
        
        Vector dati = GestioneAnagDip.leggiOspiti();
        
        jPanelCheckBoxes.setVisible(false);
        jLabelInfo.setText("");
        jTable1.setModel(new DefaultTableModel(dati, colonne));
        jButtonAggiungi.setEnabled(false);
        jButtonStipendio.setEnabled(false);
    }
    
    private void registroDipendenti() throws SQLException{
        
        Vector colonne = new Vector();
        colonne.add("Nome");
        colonne.add("Cognome");
        colonne.add("Codice fiscale");
        colonne.add("Stipendio");
        colonne.add("Data assunzione");
        colonne.add("Mansione");
        
        Vector dati = GestioneAnagDip.letturaCompletaDipendenti();
        
        jTable1.setModel(new DefaultTableModel(dati, colonne));
        jButtonAggiungi.setEnabled(true);
        jButtonStipendio.setEnabled(true);
        dipendente = true;
        jLabelInfo.setText("Media stipendi: "+GestioneAnagDip.getAvgStipendio());
        jPanelCheckBoxes.setVisible(false);
    }
    
    private void registroDitteEsterne() throws SQLException{
        
        Vector colonne = new Vector();
        colonne.add("Partita IVA");
        colonne.add("Nome");
        colonne.add("Sede");
        colonne.add("Recapito");
        
        Vector dati = GestioneDitte.leggiDitteComplete();
        
        jTable1.setModel(new DefaultTableModel(dati, colonne));
        jButtonAggiungi.setEnabled(true);
        jButtonStipendio.setEnabled(false);
        dipendente = false;
        jLabelInfo.setText("");
        jPanelCheckBoxes.setVisible(false);
    }
    
    private void registroTask() throws SQLException{
        
        Vector colonne = new Vector();
        colonne.add("ID");
        colonne.add("Operazione");
        colonne.add("Stanza");
        colonne.add("Partita IVA");
        colonne.add("Codice fiscale");
        colonne.add("Costo");
        colonne.add("Data inizio");
        colonne.add("Data fine");
                
        Vector dati = GestioneTask.storicoTask(mode);
        jLabelInfo.setText("");
        jTable1.setModel(new DefaultTableModel(dati, colonne));
        jPanelCheckBoxes.setVisible(true);
        jButtonAggiungi.setEnabled(false);
        jButtonStipendio.setEnabled(false);
        
    }
    
    
}
